# Notes

In [1]:
## Point selection after nearest location isn't random, defaults to lowest value index

# Imports

In [2]:
##IMPORTS
import numpy as np
from numpy import *
import copy

# Take in or create input

In [3]:
## FOR THE BIG 600 CELL ONE
import csv

with open("sixhundredcell_3_corrected.csv") as file_name:
    inputMatrixFull = np.loadtxt(file_name, dtype = 'int', delimiter=",")
    
    
    
inputMatrix = inputMatrixFull[480:]

    
## FOR SMALLER TESTING SOLIDS
#inputMatrix  = 



    
print(inputMatrix)


[[ 25  27  28  32]
 [ 25  26  28  30]
 [ 25  26  27  29]
 [ 26  27  28  31]
 [ 25  26  27  28]
 [ 25  36  37  39]
 [ 35  37  38  39]
 [ 33  36  37  38]
 [ 34  36  38  39]
 [ 36  37  38  39]
 [ 33  40  42  44]
 [ 33  41  42  45]
 [ 33  40  41  43]
 [ 40  41  42  46]
 [ 33  40  41  42]
 [ 26  49  50  52]
 [ 48  50  51  52]
 [ 40  49  50  51]
 [ 47  49  51  52]
 [ 49  50  51  52]
 [ 27  56  57  58]
 [ 55  57  58  59]
 [ 54  56  57  59]
 [ 53  56  58  59]
 [ 56  57  58  59]
 [ 34  60  61  63]
 [ 34  53  61  64]
 [ 34  53  60  62]
 [ 53  60  61  65]
 [ 34  53  60  61]
 [ 41  68  69  70]
 [ 67  69  70  71]
 [ 60  68  69  71]
 [ 66  68  70  71]
 [ 68  69  70  71]
 [ 47  66  72  74]
 [ 47  54  72  75]
 [ 47  54  66  73]
 [ 54  66  72  76]
 [ 47  54  66  72]
 [ 28  80  81  82]
 [ 79  81  82  83]
 [ 78  80  81  83]
 [ 77  80  82  83]
 [ 80  81  82  83]
 [ 35  84  85  87]
 [ 35  77  85  88]
 [ 35  77  84  86]
 [ 77  84  85  89]
 [ 35  77  84  85]
 [ 42  92  93  94]
 [ 91  93  94  95]
 [ 84  92  9

# Create master array for which faces have and haven't been covered

In [4]:
## Create Master Array of Uncovered Faces
## Will be removed from throughout process
masterUncoveredFaces = copy.deepcopy(inputMatrix)
#print(masterUncoveredFaces)

##Create Master Array for covered faces, starts empty, fills to be inputMatrix
rows, cols = (1, len(inputMatrix[0]))
masterCoveredFaces = [[-1 for i in range(cols)] for j in range(rows)]
#print(masterCoveredFaces)

# Find total number of vertices

In [5]:
## Find number of vertices
inputMatrixWidth= len(inputMatrix[0])
maxVert = 0
for x in inputMatrix:
    if x[inputMatrixWidth-1] > maxVert:
        maxVert = x[inputMatrixWidth-1]

print(maxVert)

120


# Creating the Dictionary of each face that touches each vertex

In [6]:
## Create list of faces touched by each vertex, as well as copy for strictly uncovered

## How to know how many faces each vertex will touch? **************************
    ## For platonic solid, equal for all, so find max faces for one, for all
    ## Just make it a dictionary, probably better
   

vertexDictOfTouchedFaces = {
    
}

for nextVertex in range(maxVert):
    vertexDictOfTouchedFaces[nextVertex+1] = []
    
## Fill in the dictionary
for currentFace in inputMatrix:
    for currentVertex in currentFace:
            vertexDictOfTouchedFaces[currentVertex].append(currentFace)
            
#print(vertexDictOfTouchedFaces)


##Create the dictionary for each uncovered face, will be removed from throughout the process
vertexDictOfTouchingUncoveredFaces = copy.deepcopy(vertexDictOfTouchedFaces)

#print(vertexDictOfTouchedFaces[8])

vertexDictOfTouchedFacesEnding = {}
for nextVertex in range(maxVert):
    vertexDictOfTouchedFacesEnding[nextVertex+1] = []
    
## Fill in the dictionary
for currentFace in inputMatrixFull:
    for currentVertex in currentFace:
            vertexDictOfTouchedFacesEnding[currentVertex].append(currentFace)
            
print(vertexDictOfTouchingUncoveredFaces)

{1: [], 2: [], 3: [], 4: [], 5: [], 6: [], 7: [], 8: [], 9: [], 10: [], 11: [], 12: [], 13: [], 14: [], 15: [], 16: [], 17: [], 18: [], 19: [], 20: [], 21: [], 22: [], 23: [], 24: [], 25: [array([25, 27, 28, 32]), array([25, 26, 28, 30]), array([25, 26, 27, 29]), array([25, 26, 27, 28]), array([25, 36, 37, 39])], 26: [array([25, 26, 28, 30]), array([25, 26, 27, 29]), array([26, 27, 28, 31]), array([25, 26, 27, 28]), array([26, 49, 50, 52])], 27: [array([25, 27, 28, 32]), array([25, 26, 27, 29]), array([26, 27, 28, 31]), array([25, 26, 27, 28]), array([27, 56, 57, 58])], 28: [array([25, 27, 28, 32]), array([25, 26, 28, 30]), array([26, 27, 28, 31]), array([25, 26, 27, 28]), array([28, 80, 81, 82])], 29: [array([25, 26, 27, 29]), array([29, 36, 43, 62]), array([29, 43, 49, 73]), array([29, 56, 62, 73]), array([29, 43, 62, 73])], 30: [array([25, 26, 28, 30]), array([30, 44, 50, 97]), array([30, 37, 44, 86]), array([30, 80, 86, 97]), array([30, 44, 86, 97])], 31: [array([26, 27, 28, 31]), 

# Create Dictionary Of Which Vertices a Single Vertex shares edges with

In [7]:
##Create something that stores every vertex, and each other vertex it shares an edge with
    ## shares edge if it shares 2 faces
    ##Look in vertexDictOfTouchedFaces, keep count of each time each vertex appears. If > 1 and not the original, edge
##What to store in, dict doesn't seem to be working well, hard with arrays as values
    ## Dict for now
    
vertexDictOfSharedEdges = {}

for nextVertex in range(maxVert):
    vertexDictOfSharedEdges[nextVertex+1] = []



rows, cols = (maxVert, maxVert)
vertexSharedFacesCount = [[0 for i in range(cols)] for j in range(rows)]
#print(len(vertexSharedFacesCount)*len(vertexSharedFacesCount[0]))



for currentVertex in vertexDictOfTouchedFaces:
    
    #print(currentVertex, vertexDictOfTouchedFaces[currentVertex])
    for currentFace in vertexDictOfTouchedFaces[currentVertex]:
        for vertexOnFace in currentFace:
            vertexSharedFacesCount[currentVertex-1][vertexOnFace-1] += 1
            if vertexSharedFacesCount[currentVertex-1][vertexOnFace-1] > 1 and vertexOnFace not in vertexDictOfSharedEdges[currentVertex]:
                    if vertexOnFace != currentVertex:
                        vertexDictOfSharedEdges[currentVertex].append(vertexOnFace)
    
    ##PUT THIS INSIDE LOOP ABOVE, SO TO ACCESS THE VALUE OF vertexOnFace
    ## Also, use number of faces each vertex is on to eliminate vertices pairing wiht self
    ##for x in vertexSharedFacesCount[currentVertex-1]:
        ##if x > 1:
            ##print(x, currentVertex)
            


#print(vertexSharedFacesCount)
#print(vertexDictOfSharedEdges)

tempVertexDictOfSharedEdges = copy.deepcopy(vertexDictOfSharedEdges)
#print(tempVertexDictOfSharedEdges)

#Once this removes an element from the dictionary, it doesn't check the next value. use temp dictionary
for currentVertex in vertexDictOfSharedEdges:
    for connectedVertex in vertexDictOfSharedEdges[currentVertex]:
        #print(currentVertex, connectedVertex)
        if connectedVertex == currentVertex:
            tempVertexDictOfSharedEdges[currentVertex].remove(connectedVertex)
            #print("removed", connectedVertex)
            
#print(vertexDictOfSharedEdges)

vertexDictOfSharedEdges = copy.deepcopy(tempVertexDictOfSharedEdges)
    
print(vertexDictOfSharedEdges)  







{1: [], 2: [], 3: [], 4: [], 5: [], 6: [], 7: [], 8: [], 9: [], 10: [], 11: [], 12: [], 13: [], 14: [], 15: [], 16: [], 17: [], 18: [], 19: [], 20: [], 21: [], 22: [], 23: [], 24: [], 25: [28, 26, 27], 26: [25, 27, 28], 27: [25, 26, 28], 28: [25, 26, 27], 29: [43, 62, 73], 30: [44, 86, 97], 31: [99, 75, 103], 32: [88, 64, 104], 33: [42, 40, 41], 34: [61, 53, 60], 35: [85, 77, 84], 36: [37, 38, 39], 37: [39, 36, 38], 38: [37, 36, 39], 39: [37, 36, 38], 40: [33, 41, 42], 41: [33, 40, 42], 42: [33, 40, 41], 43: [29, 62, 73], 44: [97, 30, 86], 45: [87, 63, 113], 46: [98, 74, 114], 47: [72, 54, 66], 48: [96, 78, 90], 49: [50, 51, 52], 50: [52, 49, 51], 51: [50, 49, 52], 52: [50, 49, 51], 53: [34, 60, 61], 54: [47, 66, 72], 55: [101, 79, 102], 56: [57, 58, 59], 57: [58, 56, 59], 58: [57, 56, 59], 59: [57, 56, 58], 60: [34, 53, 61], 61: [34, 53, 60], 62: [29, 43, 73], 63: [45, 87, 113], 64: [32, 88, 104], 65: [76, 105, 115], 66: [47, 54, 72], 67: [112, 91, 107], 68: [69, 70, 71], 69: [70, 68,

# Vertex Shared Edges Ending

In [8]:
##Create something that stores every vertex, and each other vertex it shares an edge with
    ## shares edge if it shares 2 faces
    ##Look in vertexDictOfTouchedFaces, keep count of each time each vertex appears. If > 1 and not the original, edge
##What to store in, dict doesn't seem to be working well, hard with arrays as values
    ## Dict for now
    
vertexDictOfSharedEdgesEnding = {}

for nextVertex in range(maxVert):
    vertexDictOfSharedEdgesEnding[nextVertex+1] = []


rows, cols = (maxVert, maxVert)
vertexSharedFacesCountEnding = [[0 for i in range(cols)] for j in range(rows)]
#print(len(vertexSharedFacesCount)*len(vertexSharedFacesCount[0]))



for currentVertex in vertexDictOfTouchedFacesEnding:
    
    #print(currentVertex, vertexDictOfTouchedFaces[currentVertex])
    for currentFace in vertexDictOfTouchedFacesEnding[currentVertex]:
        for vertexOnFace in currentFace:
            vertexSharedFacesCountEnding[currentVertex-1][vertexOnFace-1] += 1
            if vertexSharedFacesCountEnding[currentVertex-1][vertexOnFace-1] > 1 and vertexOnFace not in vertexDictOfSharedEdgesEnding[currentVertex]:
                    if vertexOnFace != currentVertex:
                        vertexDictOfSharedEdgesEnding[currentVertex].append(vertexOnFace)
    
    ##PUT THIS INSIDE LOOP ABOVE, SO TO ACCESS THE VALUE OF vertexOnFace
    ## Also, use number of faces each vertex is on to eliminate vertices pairing wiht self
    ##for x in vertexSharedFacesCount[currentVertex-1]:
        ##if x > 1:
            ##print(x, currentVertex)
            


#print(vertexSharedFacesCount)
#print(vertexDictOfSharedEdges)

tempVertexDictOfSharedEdgesEnding = copy.deepcopy(vertexDictOfSharedEdgesEnding)
#print(tempVertexDictOfSharedEdges)

#Once this removes an element from the dictionary, it doesn't check the next value. use temp dictionary
for currentVertex in vertexDictOfSharedEdgesEnding:
    for connectedVertex in vertexDictOfSharedEdgesEnding[currentVertex]:
        #print(currentVertex, connectedVertex)
        if connectedVertex == currentVertex:
            tempVertexDictOfSharedEdgesEnding[currentVertex].remove(connectedVertex)
            #print("removed", connectedVertex)
            
#print(vertexDictOfSharedEdges)

vertexDictOfSharedEdgesEnding = copy.deepcopy(tempVertexDictOfSharedEdgesEnding)
    
print(vertexDictOfSharedEdgesEnding)

{1: [29, 43, 25, 26, 36, 37, 33, 40, 49, 50, 30, 44], 2: [29, 62, 25, 27, 36, 39, 34, 53, 56, 58, 32, 64], 3: [43, 73, 40, 41, 49, 51, 47, 66, 68, 70, 46, 74], 4: [43, 62, 36, 38, 33, 41, 68, 69, 34, 60, 45, 63], 5: [29, 73, 26, 27, 49, 52, 47, 54, 56, 57, 31, 75], 6: [62, 73, 56, 59, 53, 60, 68, 71, 54, 66, 65, 76], 7: [86, 97, 80, 83, 77, 84, 92, 95, 78, 90, 89, 100], 8: [44, 86, 37, 38, 33, 42, 92, 93, 35, 84, 45, 87], 9: [30, 97, 26, 28, 80, 81, 78, 48, 50, 52, 31, 99], 10: [44, 97, 40, 42, 92, 94, 90, 48, 50, 51, 46, 98], 11: [30, 86, 25, 28, 37, 39, 35, 77, 80, 82, 32, 88], 12: [87, 113, 84, 85, 108, 111, 107, 91, 93, 95, 89, 116], 13: [45, 113, 41, 42, 69, 70, 67, 91, 93, 94, 46, 114], 14: [63, 87, 38, 39, 34, 61, 108, 109, 35, 85, 64, 88], 15: [63, 113, 60, 61, 108, 110, 107, 67, 69, 71, 65, 115], 16: [98, 114, 94, 95, 90, 96, 117, 120, 91, 112, 100, 116], 17: [74, 98, 51, 52, 47, 72, 117, 118, 48, 96, 75, 99], 18: [74, 114, 70, 71, 66, 72, 117, 119, 67, 112, 76, 115], 19: [99,

# Fill out matrix of vertex to vertex distances

In [9]:
rows, cols = (maxVert, maxVert)
vertexToVertexDistance = [[999 for i in range(cols)] for j in range(rows)]
#print(vertexToVertexDistance)

for i in range(0,maxVert):
    vertexToVertexDistance[i][i] = 0

#print( vertexToVertexDistance)

edgesAway = 1

while np.max(vertexToVertexDistance) == 999:
    for vertex in vertexDictOfSharedEdgesEnding:
        for secondVertex in vertexDictOfSharedEdgesEnding:
            if vertexToVertexDistance[vertex-1][secondVertex-1] == edgesAway-1:
                #print(secondVertex, " is ", edgesAway, " away")
                for vertXAway in vertexDictOfSharedEdgesEnding[secondVertex]:
                    if vertexToVertexDistance[vertex-1][vertXAway-1] == 999:
                        vertexToVertexDistance[vertex-1][vertXAway-1] = edgesAway
    edgesAway += 1
#print(vertexToVertexDistance)
  
print(vertexToVertexDistance)
#print(np.amax(vertexToVertexDistance))

[[0, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2, 4, 3, 3, 4, 4, 3, 4, 4, 3, 4, 4, 4, 5, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 3, 3, 4, 2, 3, 3, 3, 3, 3, 2, 3, 3, 4, 3, 4, 2, 3, 3, 3, 3, 2, 3, 3, 4, 3, 3, 4, 2, 3, 3, 3, 3, 3, 2, 3, 3, 4, 3, 4, 2, 3, 3, 3, 3, 2, 3, 3, 4, 4, 4, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 4, 4, 4, 4, 4, 4], [2, 0, 3, 2, 2, 2, 4, 3, 3, 4, 2, 4, 4, 2, 3, 5, 4, 4, 4, 2, 3, 3, 2, 4, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 3, 3, 3, 2, 3, 3, 4, 3, 4, 2, 3, 3, 3, 1, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 3, 4, 2, 3, 3, 3, 3, 2, 4, 3, 3, 3, 4, 3, 3, 3, 2, 3, 3, 3, 3, 3, 2, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 3, 4, 3, 3, 3, 2, 3, 4, 4, 3, 2, 3, 3, 4, 3, 4, 3, 4, 4, 4, 4, 4], [2, 3, 0, 2, 2, 2, 4, 3, 3, 2, 4, 4, 2, 4, 3, 3, 2, 2, 4, 4, 3, 5, 4, 4, 3, 2, 3, 3, 2, 3, 3, 4, 2, 3, 4, 2, 3, 3, 3, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 3, 2, 4, 2, 3, 3, 3, 2, 3, 2, 3, 4, 3, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 4, 3, 4, 4, 4, 4, 4, 4, 4, 3, 3, 4, 4, 3, 3, 3

# Tiebreaker: Calculate the distance from each maxUntouchedVertex to a covered face

In [10]:
## Create function for running calucations on each vertex in an input list
## Simply returns which of the input vertices is closest

## Premake the matrix of distances

## When called, search through covered faces
## Pull out every vertex in the covered faces sets

## For each maxUntouchedVertex, find distance each vertex in covered faces sets, take min
## Store min as distance from covered faces

## Find maxUntouchedVertex with smallest distance from covered faces

## Return that maxUntouchedVertex

def findNextVertex(listOfMaxedFaceVerts):
    
    ## Fill out all vert touching a covered face
    verticesTouchingCoveredFaces = []
    for coveredFace in masterCoveredFaces:
        for vertex in coveredFace:
            if vertex not in verticesTouchingCoveredFaces:
                #print( vertex, "isn't in verticesTouchingCoveredFaces")
                verticesTouchingCoveredFaces.append(vertex)
                #print("verticesTouchingCoveredFaces is now ", verticesTouchingCoveredFaces)
    dictOfMaxedVertDistanceToFace = {}            
    for vertex in listOfMaxedFaceVerts:
        dictOfMaxedVertDistanceToFace[vertex] = []
        closestDistance = 999999
        for vertOnFace in verticesTouchingCoveredFaces:
            if vertexToVertexDistance[vertex-1][vertOnFace -1] < closestDistance:
                closestDistance = vertexToVertexDistance[vertex-1][vertOnFace -1]
        #print(vertex, closestDistance)
        dictOfMaxedVertDistanceToFace[vertex] = closestDistance
            
        
    #print(dictOfMaxedVertDistanceToFace)

    ## Find maxUntouchedVertex with smallest distance from covered faces
    closestVert = 9999
    closestVertDist = 9999
    
    for vertex in dictOfMaxedVertDistanceToFace:
        if dictOfMaxedVertDistanceToFace[vertex] < closestVertDist:
            closestVert = vertex
            closestVertDist = dictOfMaxedVertDistanceToFace[vertex]
    return(closestVert)

# New Tiebreaker

In [11]:
## For each maxed vertex, find distance to each covered faces
## Can refernce to vertexToVertex for distances I think
## Find minimum dist to touched face, and count how mnay faces are that distance
## Can have 2d array that holds info
    ## 3 Columns, vertex, minDist, and countOfMinDist

def findNextVertexFixed(listOfMaxedFaceVerts):
    
    ## Fill out all vert touching a covered face
    verticesTouchingCoveredFaces = []
    for coveredFace in masterCoveredFaces:
        for vertex in coveredFace:
            if vertex not in verticesTouchingCoveredFaces:
                #print( vertex, "isn't in verticesTouchingCoveredFaces")
                verticesTouchingCoveredFaces.append(vertex)
                #print("verticesTouchingCoveredFaces is now ", verticesTouchingCoveredFaces)
                
    ##for each maxUntouched, find distance to each verticesTouchingCoveredFaces
    dictOfMaxedVertDistanceToCoveredFaces = {}            
    for vertex in listOfMaxedFaceVerts:
        dictOfMaxedVertDistanceToCoveredFaces[vertex] = []
        for vertOnFace in verticesTouchingCoveredFaces:
            dictOfMaxedVertDistanceToCoveredFaces[vertex] = np.append(dictOfMaxedVertDistanceToCoveredFaces[vertex], vertexToVertexDistance[vertex-1][vertOnFace -1])
            dictOfMaxedVertDistanceToCoveredFaces[vertex] = dictOfMaxedVertDistanceToCoveredFaces[vertex].astype(int)
    #print("")
    #print("dictOfMaxedVertDistanceToCoveredFaecs is now:")
    #print(dictOfMaxedVertDistanceToCoveredFaces)
    #print("")
    
    ##Find total minimum distance to a covered face
    minDist = 999999
    for x in dictOfMaxedVertDistanceToCoveredFaces:
        if min(dictOfMaxedVertDistanceToCoveredFaces[x]) < minDist:
            minDist = min(dictOfMaxedVertDistanceToCoveredFaces[x])
            
    #print("")
    #print("min distance is", minDist)
    #print("")
    
    
    ##For each maxUntouched find how many faces are the minimum distances away
    ##Store # of faces closest to maxedVerts
    dictOfNumberClosestFaces = {}
    for vertex in dictOfMaxedVertDistanceToCoveredFaces:
        dictOfNumberClosestFaces[vertex] = []
        count = (dictOfMaxedVertDistanceToCoveredFaces[vertex] == minDist).sum()
        dictOfNumberClosestFaces[vertex] = count
    #print("Lookie here" , dictOfNumberClosestFaces)
    maxedClosestFaces = max(dictOfNumberClosestFaces.values())
        
        ## Stores all maxed
    vertsToChooseFrom = []
    for vertex in dictOfNumberClosestFaces:
        if dictOfNumberClosestFaces.get(vertex) == maxedClosestFaces:
            vertsToChooseFrom = np.append(vertsToChooseFrom, vertex)
    vertsToChooseFrom = vertsToChooseFrom.astype(int)
    ##Pick one randomly / take smallest or largest
    closestVert = random.choice(vertsToChooseFrom)
    #closestVert = vertsToChooseFrom[0]
        
    return(closestVert)

# Randomly select starting vertex

In [12]:
## Select Random Starting vertex
startingVertex = random.randint(25,maxVert+1)
lastVisitedVertex = copy.deepcopy(startingVertex)
solutionVertices = list()


In [13]:
import time

tic = time.time()

print("We are starting at " , startingVertex)
continueAddingVertices = True

while continueAddingVertices == True:
    
    
    ## Add vertex to a solution attempt
    solutionVertices.append(lastVisitedVertex)
    #print(solutionVertices)
    
    
    # Processes Faces Touched by current vertex
    # Counts faces as covered for master array
    # Removes face from each vertex's untouched faces dictionary
    
    ## Find touched faces
    currentTouchedFaces = vertexDictOfTouchedFaces[lastVisitedVertex]
    #print(currentTouchedFaces)


    ## Count all as "covered"
        ## Add to a set of "covered faces"
    ##Needed to set size of array, make sure to remove later!!!!!!!!!!!!!!!!!!!!!!!!
    facesToBeAdded = np.ndarray(shape = (1, len(inputMatrix[0])))
    facesToBeAdded.fill(-1)
    facesToBeAdded = facesToBeAdded.astype(int)
    for x in currentTouchedFaces:
        facesToBeAdded = np.vstack([facesToBeAdded, x])

    #print(facesToBeAdded)

    masterCoveredFaces = np.vstack([masterCoveredFaces, facesToBeAdded])

    ##Removes the size setting rows
    removed = (masterCoveredFaces == -1).sum(1)
    fixed = masterCoveredFaces[removed == 0, :]


    masterCoveredFaces = copy.deepcopy(fixed)

    #print(masterCoveredFaces)



    ## Remove from the current vertex's list of uncovered faces
    for x in vertexDictOfTouchingUncoveredFaces:
        ##make temp
        tempXTouchingUncovered = np.ndarray(shape = (1, len(inputMatrix[0])))
        tempXTouchingUncovered.fill(-1)
        tempXTouchingUncovered = tempXTouchingUncovered.astype(int)
        for y in vertexDictOfTouchingUncoveredFaces[x]:
            ## make inZ
            inZ = False
            for z in vertexDictOfTouchedFaces[lastVisitedVertex]:
                if np.array_equal(y,z):
                    #Set inZ to true
                    inZ = True
                    #print("These are equal")
            ## if not inZ, add to temp
            if not inZ:
                tempXTouchingUncovered = np.vstack([tempXTouchingUncovered, y])
        ## fix temp
            #print(tempXTouchingUncovered)
            removed = (tempXTouchingUncovered == -1).sum(1)
            fixed = tempXTouchingUncovered[removed == 0, :]
            #print("Temp list ", x, fixed)
            tempXTouchingUncovered = copy.deepcopy(fixed)
        
        
        removed = (tempXTouchingUncovered == -1).sum(1)
        fixed = tempXTouchingUncovered[removed == 0, :]
        #print(x, fixed)
        tempXTouchingUncovered = copy.deepcopy(fixed)

        ## make temp x's uncovered touching
        #print("Our temp stuff is: ", x,tempXTouchingUncovered)
        vertexDictOfTouchingUncoveredFaces[x] = copy.deepcopy(tempXTouchingUncovered)
        #print("this",vertexDictOfTouchingUncoveredFaces[x])



    #print(vertexDictOfTouchingUncoveredFaces[lastVisitedVertex])
    
    
    
    
    
    
    # Removes faces touched by current vertex from master uncovered array
    ## Remove touched faces from "uncovered" list of faces
    ## Removing is hard when not sure which row location removing from.
    ## Maybe try just rewriting without the covered ones?

    #tempUncoveredFaces = array([[-1,-1,-1,-1]])
    tempUncoveredFaces = np.ndarray(shape = (1, len(inputMatrix[0])))
    tempUncoveredFaces.fill(-1)
    tempUncoveredFaces = tempUncoveredFaces.astype(int)
    #print(vertexDictOfTouchingUncoveredFaces)

    for x in masterUncoveredFaces:
        inY = False
        for y in vertexDictOfTouchedFaces[lastVisitedVertex]:
            #print(vertexDictOfTouchedFaces[lastVisitedVertex])
            if np.array_equal(x,y):
                inY = True
        if not inY:
            tempUncoveredFaces = np.vstack([tempUncoveredFaces,x])
    #print(tempUncoveredFaces)

    removed = (tempUncoveredFaces == -1).sum(1)
    fixed = tempUncoveredFaces[removed == 0, :]

    masterUncoveredFaces = copy.deepcopy(fixed)

    #print("Faces Not Yet Covered") 
    #print(masterUncoveredFaces)
    #print("")
    #print("Faces covered") 
    #print(masterCoveredFaces)
    #print("")
    
      ## If yes, output list of vertices as solution
    ## Covered face must be 1 version of all, and uncovered must be empty
    if len(masterUncoveredFaces) == 0:
        print("Solution Set")
        print(solutionVertices)
        print(len(solutionVertices), " vertices in solution set")
        #print( " ")
        #print("Uncoverd faces")
        #print(masterUncoveredFaces)
        #print( " ")
        #print("Covered Faces")
        #print(masterCoveredFaces)
        continueAddingVertices = False
        break
    
    
    #print(lastVisitedVertex)
    ## If no, select next Vertex
        
        
    # Find all vertices with highest uncovered faces
    
    ## Finding Next Vertex
    ## Find all vertices that touch maximum number of uncovered faces
    
    #print(vertexDictOfTouchingUncoveredFaces)
    
    maxUntouched = 0
    maxUntouchedVerts = []
    for x in vertexDictOfTouchingUncoveredFaces:
        if x not in range(25): ###########################################################################################
            if len(vertexDictOfTouchingUncoveredFaces[x]) > maxUntouched:
                maxUntouched = len(vertexDictOfTouchingUncoveredFaces[x])
            #print(x, len(vertexDictOfTouchingUncoveredFaces[x]))
            #print("max ", maxUntouched )

    for x in vertexDictOfTouchingUncoveredFaces:
        if x not in range(25):############################################################################################
            if len(vertexDictOfTouchingUncoveredFaces[x]) == maxUntouched:
                    maxUntouchedVerts.append(x)
    print("Vertices with maximum untouched faces, [", maxUntouched, "] are: ",maxUntouchedVerts)
    #print(maxUntouchedVerts[0])


        ## Calculate which of vertices in previous step are closest to a covered face 
    if len(maxUntouchedVerts) == 1:
        lastVisitedVertex = maxUntouchedVerts[0]
    elif len(maxUntouchedVerts) == 0:
        print("SOMETHING IS VERY WRONG HERE, NO MAXIMIZED VERTS")
    else:
        lastVisitedVertex = findNextVertexFixed(maxUntouchedVerts)
        print("We are now going to ",lastVisitedVertex)


    #print("The next vertex is" , lastVisitedVertex)

    
    # Check if all faces covered, if yes, print out solution, covered and uncovered
    ## Check if all faces covered
    #print(inputMatrix)
    #print(masterCoveredFaces)
    #print(np.array_equal(inputMatrix, masterCoveredFaces))

toc = time.time()

print(toc - tic)
  


We are starting at  52
Vertices with maximum untouched faces, [ 5 ] are:  [25, 27, 28, 29, 30, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]
We are now going to  40
Vertices with maximum untouched faces, [ 5 ] are:  [25, 27, 28, 29, 30, 32, 34, 35, 36, 37, 38, 39, 45, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]
We are now going to  103
Vertices with maximum untouched faces, [ 5 ] are:  [25, 27, 28, 29, 30, 32, 34, 35, 36, 37, 38, 39, 45, 53, 54, 56, 58, 59

In [14]:
fullSolution = set(list(range(1,25))).union(set(solutionVertices))
print(fullSolution)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 28, 29, 34, 37, 40, 45, 52, 54, 58, 65, 67, 68, 74, 83, 84, 88, 94, 96, 97, 101, 103, 108, 116, 119}


In [15]:
solutionConnections = {}

for i in fullSolution:
    solutionConnections[i] = []
    for j in vertexDictOfSharedEdgesEnding[i]:
        
        if j in fullSolution:
            solutionConnections[i].append(j)
print(solutionConnections)

for i in solutionConnections:
    print(i, len(solutionConnections[i]))

{1: [29, 37, 40], 2: [29, 34, 58], 3: [40, 68, 74], 4: [68, 34, 45], 5: [29, 52, 54], 6: [68, 54, 65], 7: [97, 83, 84], 8: [37, 84, 45], 9: [97, 28, 52], 10: [97, 40, 94], 11: [28, 37, 88], 12: [84, 108, 116], 13: [45, 67, 94], 14: [34, 108, 88], 15: [108, 67, 65], 16: [94, 96, 116], 17: [74, 52, 96], 18: [74, 119, 67], 19: [103, 83, 96], 20: [103, 28, 58], 21: [103, 54, 119], 22: [88, 83, 101], 23: [58, 101, 65], 24: [101, 119, 116], 28: [9, 11, 20], 29: [1, 2, 5], 34: [2, 4, 14], 37: [1, 8, 11], 40: [1, 3, 10], 45: [4, 8, 13], 52: [5, 9, 17], 54: [5, 6, 21], 58: [2, 20, 23], 65: [6, 15, 23], 67: [13, 15, 18], 68: [3, 4, 6], 74: [3, 17, 18], 83: [7, 19, 22], 84: [7, 8, 12], 88: [11, 14, 22], 94: [10, 13, 16], 96: [16, 17, 19], 97: [7, 9, 10], 101: [22, 23, 24], 103: [19, 20, 21], 108: [12, 14, 15], 116: [12, 16, 24], 119: [18, 21, 24]}
1 3
2 3
3 3
4 3
5 3
6 3
7 3
8 3
9 3
10 3
11 3
12 3
13 3
14 3
15 3
16 3
17 3
18 3
19 3
20 3
21 3
22 3
23 3
24 3
28 3
29 3
34 3
37 3
40 3
45 3
52 3
54 3


In [17]:
for x in vertexDictOfSharedEdges:
    if x not in range(25):
        print(x)

25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120


In [18]:
np.min(inputMatrix)

25